# Use Docker-in-Docker as base
FROM docker:24-dind

# Install Python properly on Alpine
RUN apk add --no-cache python3 py3-pip && \
    python3 -m ensurepip && \
    pip3 install --upgrade pip

WORKDIR /app




# Copy app
COPY . .

RUN pip3 install --no-cache-dir -r requirements.txt --break-system-packages
# Start Docker daemon then Flask
CMD sh -c "dockerd & sleep 3 && gunicorn --bind 0.0.0.0:7860 app:app"
